[package]
name = "dw_vfs_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
ba2 = "3.0.1"
openmw-cfg = "0.5.1"
rayon = "1.10.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml_with_quirks = "0.8.24"
toml = "0.8.20"
walkdir = "2.5.0"
