[package]
name = "vfstool"
version = "1.0.0"
edition = "2024"
rust-version = "1.87"
description = "A command-line tool for constructing, manipulating, and introspecting virtual file systems in Rust, based on OpenMW's VFS implementation."
license = "GPL-3.0-only"
readme = "../README.md"
homepage = "https://github.com/DreamWeave-MP/vfstool"
repository = "https://github.com/DreamWeave-MP/vfstool"
keywords = ["vfs", "openmw", "gamedev", "modding", "bethesda"]

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
openmw-config = "1.0.2"
vfstool_lib = { path = "../vfstool_lib", version = "1.0", features = [
    "serialize",
    "beth-archives",
] }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
dream_archive = { version = "0.1.6", default-features = false, features = ["bsa"] }

[[bench]]
name = "validate_chain"
harness = false
