[package]
name = "vfstool_lib"
version = "1.0.0"
edition = "2024"
rust-version = "1.85"
description = "A library for constructing and manipulating virtual file systems in Rust, based on OpenMW's VFS implementation."
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/DreamWeave-MP/vfstool"
repository = "https://github.com/DreamWeave-MP/vfstool"
keywords = ["vfs", "openmw", "gamedev", "modding", "bethesda"]

[dependencies]
ahash = "0.8"
ba2 = { version = "3.0.1", optional = true }
blake3 = "1"
zip = { version = "2", optional = true }
rayon = "1.11.0"
regex = "1"
serde = { version = "1.0.225", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }
serde_yaml = { version = "0.9.34-deprecated", optional = true }
toml = { version = "0.9.7", optional = true }
walkdir = "2.5.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = []
bsa = ["dep:ba2"]
zip = ["dep:zip"]
serialize = ["dep:serde", "dep:serde_json", "dep:serde_yaml", "dep:toml"]

[[bench]]
name = "vfs_benchmarks"
harness = false
