name: Corprus Crucible Manufacturing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['*']

jobs:
  build-lib:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/libGlobalBuild.yml@v14
    secrets: inherit
    with:
      crate_names: '["vfstool_lib"]'
      dependent_repo_names: '["DreamWeave-MP/Morrobroom"]'
      generate_benchmarks: true

  build-app:
    needs: build-lib
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/rustGlobalBuild.yml@v14
    secrets: inherit
    with:
      binary_names: '["vfstool"]'
      publish_docs: false
